### ISSUE TITLE
Ok to archive?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/4dn-workflow-viz#3]
@mruffalo : I believe this repo is unused and can be moved to https://github.com/hubmapconsortium-graveyard and archived. If that is not the case, please let me know before next Wednesday, February 3. Thanks!

**Comment by mruffalo** [comment]
Correct -- feel free to move and archive it even earlier if you'd like.

**Comment by mccalluc** [comment]
Great: Can you give me admin privs, or
1) add a note to the readme
1) move to https://github.com/hubmapconsortium-graveyard
1) archive.

Whichever is easier. Thanks!

**Comment by mruffalo** [comment]
I gave you admin privileges, and attempted to move the repository, but found that I "don’t have the permission to create public repositories on hubmapconsortium-graveyard", so it might be easiest for you to move this.

**Comment by mccalluc** [comment]
Thanks! Just sent you an invite, but I'll finish this repo.
